import { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { api, Violation } from '../../src/api';
import { useAuth } from '../../src/auth';

const STATUSES = ['pending', 'resolved', 'ignored'] as const;

export default function Violations() {
  const { token } = useAuth(); const router = useRouter(); const [status, setStatus] = useState<typeof STATUSES[number]>('pending'); const [items, setItems] = useState<Violation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [unreadCount, setUnreadCount] = useState(0); const knownPendingIds = useRef(new Set<string>()); const hasLoadedPending = useRef(false);
  const load = useCallback(async () => { if (!token) return; setError(''); try { const [nextItems, unread] = await Promise.all([api.violations(token, status), api.unreadCount(token)]); if (status === 'pending') { const newItems = nextItems.filter(item => !knownPendingIds.current.has(item.instance_id)); if (hasLoadedPending.current && newItems.length) { const first = newItems[0]; const noId = first.alert_priority === 1; Alert.alert(noId ? 'URGENT: No ID person' : 'New PPE safety alert', noId ? 'Unknown person on site. Check this person immediately.' : `${first.worker_name || first.worker_number}: missing ${first.missing_ppe.join(', ') || 'required PPE'}`); } knownPendingIds.current = new Set(nextItems.map(item => item.instance_id)); hasLoadedPending.current = true; } setItems(nextItems); setUnreadCount(unread.unread_count); } catch (value) { setError(value instanceof Error ? value.message : 'Unable to load alerts'); } finally { setLoading(false); } }, [token, status]);
  useEffect(() => { setLoading(true); load(); const interval = setInterval(load, 15000); return () => clearInterval(interval); }, [load]);
  const openAlert = async (item: Violation) => { if (token && !item.is_read) { try { await api.markRead(token, item.instance_id); setItems(current => current.map(value => value.instance_id === item.instance_id ? { ...value, is_read: true } : value)); setUnreadCount(current => Math.max(0, current - 1)); } catch {} } router.push(`/violations/${item.instance_id}`); };
  const markAllRead = async () => { if (!token || !unreadCount) return; try { await api.markRead(token); setItems(current => current.map(value => ({ ...value, is_read: true }))); setUnreadCount(0); } catch (value) { Alert.alert('Unable to mark alerts read', value instanceof Error ? value.message : 'Please try again.'); } };
  return <View style={styles.page}><View style={styles.top}><View><Text style={styles.heading}>Assigned alerts</Text><Text style={styles.subheading}>No-ID alerts require an immediate site check.</Text></View><View style={styles.actions}><Pressable accessibilityLabel={`${unreadCount} unread notifications`} onPress={markAllRead} style={styles.bell}><Text style={styles.bellText}>🔔</Text>{unreadCount > 0 ? <Text style={styles.count}>{unreadCount > 99 ? '99+' : unreadCount}</Text> : null}</Pressable><Pressable onPress={() => router.push('/profile')}><Text style={styles.profile}>Profile</Text></Pressable></View></View>{unreadCount > 0 ? <Pressable onPress={markAllRead}><Text style={styles.markAll}>Mark all notifications read</Text></Pressable> : null}<View style={styles.tabs}>{STATUSES.map(value => <Pressable key={value} onPress={() => setStatus(value)} style={[styles.tab, status === value && styles.activeTab]}><Text style={[styles.tabText, status === value && styles.activeTabText]}>{value}</Text></Pressable>)}</View><ScrollView contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />}>{loading && !items.length ? <ActivityIndicator /> : null}{!!error && <Text style={styles.error}>{error}</Text>}{!loading && !items.length ? <Text style={styles.empty}>No {status} alerts assigned to you.</Text> : null}{items.map(item => <Pressable key={item.instance_id} style={[styles.card, item.alert_priority === 1 && styles.urgentCard, !item.is_read && styles.unreadCard]} onPress={() => openAlert(item)}><View style={styles.cardTop}><Text style={styles.worker}>{item.alert_priority === 1 ? 'NO ID — CHECK IMMEDIATELY' : item.worker_name || item.worker_number}</Text><View style={styles.indicators}>{!item.is_read ? <View style={styles.unreadDot} /> : null}<Text style={[styles.priority, item.alert_priority === 1 && styles.urgentPriority]}>P{item.alert_priority}</Text></View></View><Text style={styles.detail}>{item.worker_number || item.identity_status}{item.worker_team ? `  |  ${item.worker_team}` : ''}</Text><Text style={styles.ppe}>Missing: {item.missing_ppe.join(', ') || 'Required PPE'}</Text><Text style={styles.detail}>Detected {item.first_detected}  |  {item.snapshot_count} snapshots</Text></Pressable>)}</ScrollView></View>;
}

const styles = StyleSheet.create({ page:{flex:1,padding:16},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:8},heading:{fontSize:23,fontWeight:'700',color:'#172033'},subheading:{color:'#637083',marginTop:3,maxWidth:230},actions:{flexDirection:'row',alignItems:'center',gap:14},bell:{position:'relative',padding:4},bellText:{fontSize:25},count:{position:'absolute',right:-9,top:-7,minWidth:18,paddingHorizontal:4,height:18,borderRadius:9,textAlign:'center',color:'#fff',backgroundColor:'#b42318',fontSize:11,fontWeight:'800',overflow:'hidden'},profile:{color:'#1769d1',fontWeight:'700'},markAll:{alignSelf:'flex-end',color:'#1769d1',fontWeight:'700',fontSize:12,marginBottom:10},tabs:{flexDirection:'row',gap:8,marginBottom:14},tab:{flex:1,alignItems:'center',paddingVertical:9,borderRadius:5,backgroundColor:'#e9eef5'},activeTab:{backgroundColor:'#1769d1'},tabText:{textTransform:'capitalize',color:'#43516a'},activeTabText:{color:'#fff',fontWeight:'700'},list:{gap:10,paddingBottom:24},card:{backgroundColor:'#fff',borderRadius:8,padding:16,borderWidth:1,borderColor:'#dbe1ea'},unreadCard:{borderColor:'#1769d1',borderWidth:2},urgentCard:{borderColor:'#b42318',backgroundColor:'#fff5f4'},cardTop:{flexDirection:'row',justifyContent:'space-between',gap:10},worker:{fontSize:17,fontWeight:'700',color:'#172033',flexShrink:1},indicators:{flexDirection:'row',alignItems:'center',gap:7},unreadDot:{width:9,height:9,borderRadius:5,backgroundColor:'#1769d1'},priority:{paddingHorizontal:8,paddingVertical:3,borderRadius:12,fontSize:12,fontWeight:'800',overflow:'hidden',backgroundColor:'#fff0d7',color:'#8a5600'},urgentPriority:{backgroundColor:'#b42318',color:'#fff'},detail:{color:'#637083',marginTop:7,fontSize:12},ppe:{color:'#b42318',fontWeight:'700',marginTop:10},error:{color:'#b42318',backgroundColor:'#fff',padding:14,borderRadius:6},empty:{textAlign:'center',color:'#637083',marginTop:42} });
